// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foo2.web;

import com.foo2.service.api.TimerService;
import com.foo2.web.TimersItemJsonController;

privileged aspect TimersItemJsonController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     */
    public TimerService TimersItemJsonController.timerService;
    
}
